lib/mango_web/router.ex
defmodule MangoWeb.Router do
  use MangoWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug MangoWeb.Plugs.LoadCustomer
    plug MangoWeb.Plugs.FetchCart
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", MangoWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/categories/:name", CategoryController, :show

    get "/register", RegistrationController, :new
    post "/register", RegistrationController, :create

    get "/login", SessionController, :new
    post "/login", SessionController, :create

    get "/logout", SessionController, :delete

    post "/cart", CartController, :add

  end

  # Other scopes may use custom stacks.
  # scope "/api", MangoWeb do
  #   pipe_through :api
  # end
end

lib/mango_web/views/layout_view.ex
defmodule MangoWeb.LayoutView do
  use MangoWeb, :view
end

lib/mango_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Mango!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <%= render "app_nav.html", conn: @conn, customer: @current_customer %>
    <div class="container">

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/mango_web/templates/layout/app_nav.html.eex
<nav class="navbar navbar-default navbar-fixed-top">
<div class="container">
<div class="navbar-header">
<button type="button" class="navbar-toggle collapsed" datatoggle="
collapse" data-target="#primary-nav">
<span class="sr-only">Toggle navigation</span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
<span class="icon-bar"></span>
</button>
<a class="navbar-brand" href="/">
<img src="/images/logo.png"/> Mango
</a>
</div>
<div class="collapse navbar-collapse" id="primary-nav">
<ul class="nav navbar-nav">

<li><%= link "Fruits", to: category_path(@conn, :show, "fruits") %></li>
<li><%= link "Vegetables", to: category_path(@conn, :show, "vegetables") %></li>

</ul>

<ul class="nav navbar-nav navbar-right >
    <%= if @customer do %>
        <li class = "dropdown">
            <a href="#" class = "dropdown-toggle" data-toggle="dropdown">
                <%= @customer.name %><span class="caret"></span></a>
             <ul class="dropdown-menu">
                <li><%= link "Log Out", to: "/logout" %></li>
             </ul>
        </li>
    <% else %>
        <li><%= link "Register", to: registration_path(@conn, :new), class: "nav-link" %></li>
        <li><%= link "Sign in", to: session_path(@conn, :new), class: "nav-link" %></li>
    <% end %>
</ul>

</div>
</div>
</nav>